include("../src/SortedCounters.jl")
include("../src/AtomCells.jl")
include("../src/SpinConfigs.jl")
include("../src/SphericalHarmonicsTransforms.jl")
include("../src/RotationMatrix.jl")
include("../src/TesseralHarmonics.jl")
include("../src/InputSpecs.jl")
include("../src/AngularMomentumCoupling.jl")
include("../src/CoupledBases.jl")

using Magesty
using Test

const TEST_MODE = get(ENV, "TEST_MODE", "all")

if TEST_MODE in ("unit", "all")
	@testset verbose = true "component" begin
		include("./component/test_TesseralHarmonics.jl")
		include("./component/test_AngularMomentumCoupling.jl")
		include("./component/test_SortedCounter.jl")
		include("./component/test_SphericalHarmonicsTransforms.jl")
		include("./component/test_sphericart_agreement.jl")
		include("./component/test_RotationMatrix.jl")
		include("./component/test_SpinConfigs.jl")
		include("./component/test_InputSpecs.jl")
		include("./component/test_AtomCells.jl")
		include("./component/test_AtomsBaseAdapter.jl")
		include("./component/test_cluster_cutoff_criterion.jl")
		include("./component/test_Clusters.jl")
		include("./component/test_Structures.jl")
		include("./component/test_Symmetries.jl")
		include("./component/test_CoupledBases.jl")
		include("./component/test_Fitting_dispatch.jl")
		include("./component/test_fitting_estimators.jl")
		include("./component/test_fitting_solver.jl")
		include("./component/test_salc_canonical_gauge.jl")
		include("./component/test_SALC_projection.jl")
		include("./component/test_SCEBasis.jl")
		include("./component/test_SCEDataset.jl")
		include("./component/test_SCEFit.jl")
		include("./component/test_refit.jl")
		include("./component/test_gcv.jl")
		include("./component/test_fit_basis_check.jl")
		include("./component/test_energy_centered_design_matrix.jl")
		include("./component/test_design_matrix_equivalence.jl")
		include("./component/test_save_load.jl")
		include("./component/test_fitcheck_io.jl")
		include("./component/test_ExtXYZ.jl")
		include("./component/test_VaspIO.jl")
		include("./component/test_vasp_to_extxyz.jl")
		include("./component/test_poscar_to_toml.jl")
		include("./component/test_oszicar_to_embset.jl")
		include("./component/test_IncarIO.jl")
		include("./component/test_MfaSampling.jl")
		include("./component/test_sunny_export.jl")
		include("./component/test_thread_safety.jl")
	end
end
if TEST_MODE in ("integration", "all")
	@testset verbose = true "integration" begin
		include("./integration/square_lattice/test.jl")
		include("./integration/dimer/test.jl")
		include("./integration/chain/test.jl")
		include("./integration/febcc_2x2x2_pm/test.jl")
		include("./integration/fept_tetragonal_2x2x2/test.jl")
		include("./integration/fege_2x2x2/test.jl")
	end
end
if TEST_MODE in ("jet",)
	include("./jet.jl")
end
if TEST_MODE in ("aqua",)
	include("./aqua.jl")
end
