test-all:
	julia --project -e 'using Pkg; Pkg.test()'

test-unit:
	TEST_MODE=unit julia --project -e 'using Pkg; Pkg.test()'

test-integration:
	TEST_MODE=integration julia --project -e 'using Pkg; Pkg.test()'

test-tools:
	julia --project tools/test/runtests.jl

test-jet:
	TEST_MODE=jet julia --project -e 'using Pkg; Pkg.test()'

test-aqua:
	TEST_MODE=aqua julia --project -e 'using Pkg; Pkg.test()'

bench-setup:
	julia --project=bench -e 'using Pkg; Pkg.develop(path="."); Pkg.instantiate()'

bench-sphericart:
	julia --project=bench bench/benchmark_sphericart.jl

bench-salcbasis:
	julia --project=bench bench/benchmark_salcbasis_hotspots.jl

bench-spherical-harmonics:
	julia --project=bench bench/benchmark_spherical_harmonics.jl

bench-threads:
	bash bench/run_threads_scaling.sh

test-sphericart:
	TEST_MODE=sphericart julia --project -e 'using Pkg; Pkg.test()'

# Run the same checks GitHub Actions runs, locally, before pushing.
# Uses the juliaup `release` channel (matches CI's `1`, currently 1.12.x).
# CI also tests against the explicit `1.12` minimum; locally we skip the
# duplicate run because `release` resolves to the same Julia until 1.13
# stable ships. Install the channel if missing:
#   juliaup add release
ci-local:
	@# Manifest.toml is gitignored; CI starts without it, so reproduce that
	@# locally by removing the cached one before each Julia version. The
	@# manifest is regenerated by the test run, then deleted again so the
	@# next version resolves freshly.
	rm -f Manifest.toml
	julia +release --project -e 'using Pkg; Pkg.test()'
	$(MAKE) test-aqua
	$(MAKE) test-jet